use_frameworks!

target 'LinkageError_Example' do
  pod 'LinkageError', :path => '../'

  target 'LinkageError_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
