use_frameworks!
platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git''
source 'https://github.com/brightcove/BrightcoveSpecs.git'

target 'LinkageError_Example' do
  pod 'LinkageError', :path => '../'

  target 'LinkageError_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
